name: C++ CI Workflow

on:
  push:
    branches:
      - code_ci
  workflow_dispatch:
    
  pull_request:
    branches:
      - code_ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y libgtest-dev cmake
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Build project
        run: |
          make clean
          make all

      - name: Ran unit tests
        run: |
          make test

      - name: Run executable
        run: |
          ./build/game
