name: C++ CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up CCache
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ hashFiles('**/*.cpp', '**/*.h', 'CMakeLists.txt') }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ccache libgtest-dev
          # Tell CMake to use ccache as launcher
          echo 'export CCACHE_DIR=$HOME/.ccache' >> $GITHUB_ENV
          echo 'export CXX="ccache g++"'      >> $GITHUB_ENV
          echo 'export CC="ccache gcc"'       >> $GITHUB_ENV

      - name: Configure & Build
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build . -- -j$(nproc)

      - name: Smoke test with sample input
        run: |
          # Здесь пример простой команды запуска без долгих эмуляций
          echo -e "human\nknight\n" | ./build/game
