# .github/workflows/ci.yml
name: C++ Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Configure & Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build . -- -j$(nproc)

      - name: Smoke test with sample input
        run: |
          cd build
          echo -e "human\nknight\n" | ./game
