name: C++ CI Workflow.

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake libgtest-dev

      - name: Configure CMake
        run: |
          cmake -B build -S .

      - name: Build project
        run: |
          cmake --build build --config Release

      - name: Run executable
        run: |
          ./build/game
