name: C++ CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake libgtest-dev

      - name: Configure & Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build .


      - name: Smoke-run game
        run: |
          ./build/game
