name: C++ CI 

on:
  push:
    branches:
      - code_ci
    
  pull_request:
    branches:
      - code_ci
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CI
        uses: actions/checkout@v4
        with:
          ref: code_of_game

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y libgtest-dev cmake
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Build project
        run: |
          make clean
          make all

      - name: Ran unit tests
        run: |
          make test

     # - name: Run executable  убираем этот кусок, потому что игра требует неоднократного 
     #   run: |                ввода с клавиатуры и этот кусок висит.
     #     ./build/game
